//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imapi.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imapi.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate the IDiscMaster implementation..
        /// </summary>
        internal static string Error_Msg_DiscMaster_CoCreateFailed {
            get {
                return ResourceManager.GetString("Error_Msg_DiscMaster_CoCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie has been previously set..
        /// </summary>
        internal static string Error_Msg_DiscMasterProgressEvents_CookiePrevSet {
            get {
                return ResourceManager.GetString("Error_Msg_DiscMasterProgressEvents_CookiePrevSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscRecorderCollection is ReadOnly..
        /// </summary>
        internal static string Error_Msg_DiscRecorderCollection_ReadOnly {
            get {
                return ResourceManager.GetString("Error_Msg_DiscRecorderCollection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Argument.
        /// </summary>
        internal static string Error_Msg_E_INVALIDARGUMENT {
            get {
                return ResourceManager.GetString("Error_Msg_E_INVALIDARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The called method is not yet implemented..
        /// </summary>
        internal static string Error_Msg_E_NOTIMPL {
            get {
                return ResourceManager.GetString("Error_Msg_E_NOTIMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not complete the operation. Out of memory..
        /// </summary>
        internal static string Error_Msg_E_OUTOFMEMORY {
            get {
                return ResourceManager.GetString("Error_Msg_E_OUTOFMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected catastrophic failure has occurred. .
        /// </summary>
        internal static string Error_Msg_E_UNEXPECTED {
            get {
                return ResourceManager.GetString("Error_Msg_E_UNEXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was aborted because of an unspecified error..
        /// </summary>
        internal static string Error_Msg_General_E_ABORT {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general access-denied error ocurred..
        /// </summary>
        internal static string Error_Msg_General_E_ACCESSDENIED {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified failure has occurred..
        /// </summary>
        internal static string Error_Msg_General_E_FAIL {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid handle was used..
        /// </summary>
        internal static string Error_Msg_General_E_HANDLE {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more arguments are invalid. .
        /// </summary>
        internal static string Error_Msg_General_E_INVALIDARG {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_INVALIDARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QueryInterface method did not recognize the requested interface or the interface is not supported..
        /// </summary>
        internal static string Error_Msg_General_E_NOINTERFACE {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_NOINTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired method has not been implemented..
        /// </summary>
        internal static string Error_Msg_General_E_NOTIMPL {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_NOTIMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method failed to allocate necessary memory..
        /// </summary>
        internal static string Error_Msg_General_E_OUTOFMEMORY {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_OUTOFMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data necessary to Complete the operation is not yet available. .
        /// </summary>
        internal static string Error_Msg_General_E_PENDING {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid pointer was used..
        /// </summary>
        internal static string Error_Msg_General_E_POINTER {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_POINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected catastrophic failure has occurred. .
        /// </summary>
        internal static string Error_Msg_General_E_UNEXPECTED {
            get {
                return ResourceManager.GetString("Error_Msg_General_E_UNEXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method succeeded and returned the boolean value FALSE..
        /// </summary>
        internal static string Error_Msg_General_S_FALSE {
            get {
                return ResourceManager.GetString("Error_Msg_General_S_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method succeeded. If a boolean return value is expected; the returned value is TRUE..
        /// </summary>
        internal static string Error_Msg_General_S_OK {
            get {
                return ResourceManager.GetString("Error_Msg_General_S_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to IDiscMaster::Open has already been made against this object by your application..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_ALREADYOPEN {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_ALREADYOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application tried to add a badly named element to a disc..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_BADJOLIETNAME {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_BADJOLIETNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to create a bootable image on a non-blank disc..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_BOOTIMAGE_AND_NONBLANK_DISC {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_BOOTIMAGE_AND_NONBLANK_DISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the media..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_CANNOT_WRITE_TO_MEDIA {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_CANNOT_WRITE_TO_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stash is located on a Compressed volume and cannot be read..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_COMPRESSEDSTASH {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_COMPRESSEDSTASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recorder does not support an operation..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_DEVICE_INVALIDTYPE {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_DEVICE_INVALIDTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recorder does not support any properties..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_DEVICE_NOPROPERTIES {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_DEVICE_NOPROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device cannot be used or is already in use..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_DEVICE_NOTACCESSIBLE {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_DEVICE_NOTACCESSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is not present or has been removed..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_DEVICE_NOTPRESENT {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_DEVICE_NOTPRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another application is already using this device, so Imapi cannot access the device..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_DEVICE_STILL_IN_USE {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_DEVICE_STILL_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disc is full..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_DISCFULL {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_DISCFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to read disc data from the device..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_DISCINFO {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_DISCINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stash is located on an encrypted volume and cannot be read..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_ENCRYPTEDSTASH {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_ENCRYPTEDSTASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing the image file..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_FILEACCESS {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_FILEACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file to add is already in the image file and the overwrite flag was not set..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_FILEEXISTS {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_FILEEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while enabling/disabling file system access or during auto-insertion detection..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_FILESYSTEM {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_FILESYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic error occurred..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_GENERIC {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drive interface could not be initialized for closing..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_INITIALIZE_ENDWRITE {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_INITIALIZE_ENDWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drive interface could not be initialized for writing..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_INITIALIZE_WRITE {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_INITIALIZE_WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staged image is not suitable for a burn. It has been corrupted or cleared and has no usable content..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_INVALIDIMAGE {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_INVALIDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content streaming was lost; a buffer under-run may have occurred..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_LOSS_OF_STREAMING {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_LOSS_OF_STREAMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media is not a type that can be used..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_MEDIUM_INVALIDTYPE {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_MEDIUM_INVALIDTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no disc in the active recording device..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_MEDIUM_NOTPRESENT {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_MEDIUM_NOTPRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An active format master has not been selected using IDiscMaster::SetActiveDiscMasterFormat..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_NOACTIVEFORMAT {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_NOACTIVEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An active disc recorder has not been selected using IDiscMaster::SetActiveDiscRecorder..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_NOACTIVERECORDER {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_NOACTIVERECORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough free space to create the stash file on the specified volume..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_NOTENOUGHDISKFORSTASH {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_NOTENOUGHDISKFORSTASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A recorder object has not been initialized..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_NOTINITIALIZED {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_NOTINITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to IDiscMaster::Open has not been made..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_NOTOPENED {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_NOTOPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected stash location is on a removable media..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_REMOVABLESTASH {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_REMOVABLESTASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another application is already using the Imapi stash file required to stage a disc image. Try again later..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_STASHINUSE {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_STASHINUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track was too short..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_TRACK_NOT_BIG_ENOUGH {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_TRACK_NOT_BIG_ENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An audio track is not open for writing..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_TRACKNOTOPEN {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_TRACKNOTOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An open audio track is already being staged..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_TRACKOPEN {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_TRACKOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user canceled the operation..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_USERABORT {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_USERABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Imapi multi-session disc has been removed from the active recorder..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_WRONGDISC {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_WRONGDISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to IJolietDiscMaster has been made when IRedbookDiscMaster is the active format, or vice versa. To use a different format, change the format and clear the image file contents..
        /// </summary>
        internal static string Error_Msg_IMAPI_E_WRONGFORMAT {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_E_WRONGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer is too small..
        /// </summary>
        internal static string Error_Msg_IMAPI_S_BUFFER_TOO_SMALL {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_S_BUFFER_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown property was passed in a property set and it was ignored..
        /// </summary>
        internal static string Error_Msg_IMAPI_S_PROPERTIESIGNORED {
            get {
                return ResourceManager.GetString("Error_Msg_IMAPI_S_PROPERTIESIGNORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create storage..
        /// </summary>
        internal static string Error_Msg_JolietStorage_CouldNotCreateStorage {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_CouldNotCreateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter pstgPriority must be null..
        /// </summary>
        internal static string Error_Msg_JolietStorage_pstgPriority_null {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_pstgPriority_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter reserved must be 0..
        /// </summary>
        internal static string Error_Msg_JolietStorage_reserved_0 {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_reserved_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter reserved1 must be 0..
        /// </summary>
        internal static string Error_Msg_JolietStorage_Reserved1 {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_Reserved1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter reserved1 must be null..
        /// </summary>
        internal static string Error_Msg_JolietStorage_reserved1_null {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_reserved1_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter reserved2 must be null..
        /// </summary>
        internal static string Error_Msg_JolietStorage_Reserved2 {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_Reserved2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter reserved2 must be 0..
        /// </summary>
        internal static string Error_Msg_JolietStorage_reserved2_0 {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_reserved2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter reserved3 must be 0..
        /// </summary>
        internal static string Error_Msg_JolietStorage_Reserved3 {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_Reserved3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter snbExclude must be null..
        /// </summary>
        internal static string Error_Msg_JolietStorage_snbExclude_null {
            get {
                return ResourceManager.GetString("Error_Msg_JolietStorage_snbExclude_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size must be greater than 0..
        /// </summary>
        internal static string Error_Msg_ManagedIStream_BufferBiggerThanZero {
            get {
                return ResourceManager.GetString("Error_Msg_ManagedIStream_BufferBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size must be greater than 0..
        /// </summary>
        internal static string Error_Msg_PinnedByteBuffer_BufferBiggerThanZero {
            get {
                return ResourceManager.GetString("Error_Msg_PinnedByteBuffer_BufferBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least 1 byte added..
        /// </summary>
        internal static string Error_Msg_RedbookDiscMaster_AddAtLeastOneByte {
            get {
                return ResourceManager.GetString("Error_Msg_RedbookDiscMaster_AddAtLeastOneByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least 1 audio block in a track..
        /// </summary>
        internal static string Error_Msg_RedbookDiscMaster_AtLeastOneAudioBlock {
            get {
                return ResourceManager.GetString("Error_Msg_RedbookDiscMaster_AtLeastOneAudioBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least 1 byte..
        /// </summary>
        internal static string Error_Msg_RedbookDiscMaster_AtLeastOneByte {
            get {
                return ResourceManager.GetString("Error_Msg_RedbookDiscMaster_AtLeastOneByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open audio file. The file was not found..
        /// </summary>
        internal static string Error_Msg_RedbookDiscMaster_AudioFileNotFound {
            get {
                return ResourceManager.GetString("Error_Msg_RedbookDiscMaster_AudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null reference pointer was passed to the stub..
        /// </summary>
        internal static string Error_Msg_RPC_X_NULL_REF_POINTER {
            get {
                return ResourceManager.GetString("Error_Msg_RPC_X_NULL_REF_POINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested access to the property set has been denied, or, when one or more of the properties is a stream or storage object, access to that substorage or substream has been denied. The storage or stream may already be open. No properties were retrieved..
        /// </summary>
        internal static string Error_Msg_STG_E_ACCESSDENIED {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_ACCESSDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists..
        /// </summary>
        internal static string Error_Msg_STG_E_FILEALREADYEXISTS {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_FILEALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A storage-related error has occurred; specifically; a requested file does not exist..
        /// </summary>
        internal static string Error_Msg_STG_E_FILENOTFOUND {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_FILENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory exists to perform this operation. No properties were retrieved. For computers running on Windows NT 4.0 and earlier, the size limit is 256 KB. For computers running on Windows 2000, Windows XP, and Windows Server 2003, the limit is 1 MB for OLE property sets..
        /// </summary>
        internal static string Error_Msg_STG_E_INSUFFICIENTMEMORY {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_INSUFFICIENTMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the grfCommitFlags parameter is not valid..
        /// </summary>
        internal static string Error_Msg_STG_E_INVALIDFLAG {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_INVALIDFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking is not supported at all or the specific type of lock requested is not supported..
        /// </summary>
        internal static string Error_Msg_STG_E_INVALIDFUNCTION {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_INVALIDFUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property name dictionary was not found. .
        /// </summary>
        internal static string Error_Msg_STG_E_INVALIDHEADER {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_INVALIDHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is too long, it has incorrect syntax, or it has illegal characters..
        /// </summary>
        internal static string Error_Msg_STG_E_INVALIDNAME {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_INVALIDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the parameters is invalid; for example, when one of the PROPSPEC structures contains an illegal value of the ulKind member. If the ulKind member is set to a string name instead of a property set value, some properties may not be retrieved..
        /// </summary>
        internal static string Error_Msg_STG_E_INVALIDPARAMETER {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_INVALIDPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid pointer was passed..
        /// </summary>
        internal static string Error_Msg_STG_E_INVALIDPOINTER {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_INVALIDPOINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disk is full or the property-set size limit of 256 KB has been exceeded. Some properties may or may not have been written. For more information, see the Remarks section..
        /// </summary>
        internal static string Error_Msg_STG_E_MEDIUMFULL {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_MEDIUMFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STGC_ONLYIFCURRENT was specified, but the optimistic concurrency control failed..
        /// </summary>
        internal static string Error_Msg_STG_E_NOTCURRENT {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_NOTCURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to write a nonsimple (stream- or storage-valued) property to a simple property set. .
        /// </summary>
        internal static string Error_Msg_STG_E_PROPSETMISMATCHED {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_PROPSETMISMATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the storage..
        /// </summary>
        internal static string Error_Msg_STG_E_READFAULT {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_READFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property set was reverted. For example, if the property set is deleted while open, by using IPropertySetStorage::Delete, this status would be returned. .
        /// </summary>
        internal static string Error_Msg_STG_E_REVERTED {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_REVERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are insufficient resources to open another file..
        /// </summary>
        internal static string Error_Msg_STG_E_TOOMANYOPENFILES {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_TOOMANYOPENFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when writing the storage..
        /// </summary>
        internal static string Error_Msg_STG_E_WRITEFAULT {
            get {
                return ResourceManager.GetString("Error_Msg_STG_E_WRITEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 520CCA62-51A5-11D3-9144-00104BA11C5E.
        /// </summary>
        internal static string IDiscMasterGUID {
            get {
                return ResourceManager.GetString("IDiscMasterGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E3BC42CE-4E5C-11D3-9144-00104BA11C5E.
        /// </summary>
        internal static string IJolietDiscMasterGUID {
            get {
                return ResourceManager.GetString("IJolietDiscMasterGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E3BC42CD-4E5C-11D3-9144-00104BA11C5E.
        /// </summary>
        internal static string IRedbookDiscMasterGUID {
            get {
                return ResourceManager.GetString("IRedbookDiscMasterGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 520CCA63-51A5-11D3-9144-00104BA11C5E.
        /// </summary>
        internal static string MSDiscMasterObjGUID {
            get {
                return ResourceManager.GetString("MSDiscMasterObjGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pstgPriority.
        /// </summary>
        internal static string Variables_pstgPriority {
            get {
                return ResourceManager.GetString("Variables_pstgPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string Variables_reserved {
            get {
                return ResourceManager.GetString("Variables_reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved1.
        /// </summary>
        internal static string Variables_reserved1 {
            get {
                return ResourceManager.GetString("Variables_reserved1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved2.
        /// </summary>
        internal static string Variables_reserved2 {
            get {
                return ResourceManager.GetString("Variables_reserved2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved3.
        /// </summary>
        internal static string Variables_reserved3 {
            get {
                return ResourceManager.GetString("Variables_reserved3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snbExclude.
        /// </summary>
        internal static string Variables_snbExclude {
            get {
                return ResourceManager.GetString("Variables_snbExclude", resourceCulture);
            }
        }
    }
}
